### ISSUE TITLE
Fix CSS (more details in the comment)

### ISSUE THREAD

**Issue by vens8** [vens8/SymposiumCGAS#8]
Timer Section:
- Currently the text labels for the timer are misaligned. 
- Not responsive
- Design and colors a little out of place compared to the rest of the website

Timeline Schedule Section:
- The timeline schedule doesn't have margins 
- Issues with responsiveness
- Reveal animation not working as expected (refer to source: https://codepen.io/tutsplus/pen/jOBdZjL)

Note: no need to change the lorem ipsum or content anywhere, you may leave it as it is.

Issue assignment: Please comment here if you're interested in working on it and start working. I'll assign it to you.

**Comment by vens8** [comment]
@08Uzair maybe try working on this?

**Comment by vens8** [comment]
Issue hasn't been assigned to anyone, still open to all

**Comment by vens8** [comment]
@Vidhanvyrs sure I've assigned you the issue.

**Comment by vens8** [comment]
@Vidhanvyrs please try to fix it as early as possible. Thank you.

**Comment by Vidhanvyrs** [comment]
> @Vidhanvyrs please try to fix it as early as possible. Thank you.

Yes 💯

**Comment by vens8** [comment]
@Vidhanvyrs status please?
